name: {{name.snakeCase()}}
description: Feature {{classname.pascalCase()}} (couche presentation).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.10.0-0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  scores_domain:
  tactics_theme:

dev_dependencies:
  build_runner: ^2.11.1
  riverpod_generator: ^4.0.3

flutter:
  uses-material-design: true
